---
title: "Credit Card Fraud Detection"
author: "Vinh Dang"
date: "3/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Introduction

The data can be downloaded from [https://www.kaggle.com/dalpozz/creditcardfraud](https://www.kaggle.com/dalpozz/creditcardfraud). You need to unzip the data

## Loading data

```{r}
# quite slow, but OK
  credit_card = read.csv("creditcard.csv")
```

Let's take a look at the data

```{r}
  str (credit_card)
```

Let's convert the Class column to factor

```{r}
  credit_card$Class = as.factor(credit_card$Class)
```

## Prediction

### Random forest

```{r}
  library(h2o)
  h2o.init ()
  
  # First RF model
  h2o_credit = as.h2o (credit_card)
  
  divide = h2o.splitFrame(h2o_credit, ratios = 0.8)
  
  train = divide[[1]]
  test = divide[[2]]
  
  rf1 = h2o.randomForest(x=1:30,y=31, training_frame = train, validation_frame = test, ntrees = 500)
```

Let's see what do you achieve

```{r}
  rf1
```

On validation data, the very first random forest achieved the AUC of ``0.9765926`` and the F1-score of ``0.853659``.
